const weatherIconMap = {
  "01d": "bi-brightness-high",
  "01n": "bi-moon",
  "02d": "bi-cloud-sun",
  "02n": "bi-cloud-moon",
  "03d": "bi-cloud",
  "03n": "bi-cloud",
  "04d": "bi-clouds",
  "04n": "bi-clouds",
  "09d": "bi-cloud-rain",
  "09n": "bi-cloud-rain",
  "10d": "bi-cloud-drizzle",
  "10n": "bi-cloud-drizzle",
  "11d": "bi-cloud-lightning-rain",
  "11n": "bi-cloud-lightning-rain",
  "13d": "bi-cloud-snow",
  "13n": "bi-cloud-snow",
  "50d": "bi-cloud-haze",
  "50n": "bi-cloud-haze",
};
